version: '3.8'

services:
  sgi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2222:2222"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@sgi-postgres:5432/sgi
    depends_on:
      - postgres

  sgi-postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sgi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
